const BodyRu = {
  hh: "Онлайн консультации от врачей специалистов 24/7",
  p: "Проконсультируйтесь сейчас или по  предварительной записи  со своего компьютера или c помощью нашего приложения, доступного в App Store и Google Play",
  but: "Записаться",
  butt: "Как это работает?",
  bodyh: "Записаться к врачу",
  bodyp: "Более 1500 врачей и более 50 разных специализаций",
  bodyul: "Прием в удобное для вас время, без визита в клинику",
  bodyull: "Врачи с опытом работы более 8 лет",
  bodyulll: "Понятно объясним причину недуга и дадим подробную рекомендацию",
  bodybut: "МОИ ЗАПИСИ",
  bodytableA: "Предстоящие",
  bodytableB: "Прошедшие",
  bodytableC: "Отмененные",
  video: "Видео связь",
  //   contbut: "Запланировано",
  commentname: "Имя Фамилия",
  profession: "Педиатр",
  staj: "Стаж 15 лет",
  contbutt: "Посмотреть запись",
  butcont: "Посмотреть постановление",
};
const BodyEn = {
  hh: "Online consultations from specialist doctors 24/7",
  p: "Consult now or by appointment from your computer or through our app available on the App Store and Google Play.",
  but: "Enroll",
  butt: "How does it work?",
  bodyh: "Make an appointment",
  bodyp: "More than 1500 doctors and more than 50 different specialties",
  bodyul:
    "Appointments at a time that is convenient for you, without coming to the clinic",
  bodyull: "Doctors with more than 8 years of experience",
  bodyulll:
    "We will explain the cause of the ailment clearly and give a detailed recommendation",
  bodybut: "MY RECORDS",
  bodytableA: "Upcoming",
  bodytableB: "Past",
  bodytableC: "Canceled",
  //   date: "03 Mart 2021 ",
  //   hour: "16:00",
  video: "liaison",
  contbutt: "Scheduled",
  commentname: "Name Surname",
  profession: "Pediatrician",
  staj: "15 years of experience",
  //   contbutt: "View the recording",
  butcont: "View the ruling",
};

export { BodyEn, BodyRu };
