export const CommentArray = [
  {
    date: "03 Марта 2021 ",
    name: "Ольга Никитина",
    hour: "16:00",
    profession: "Педиатр",
    staj: "Стаж 15 лет",
    contbut: "Запланировано",
    contbut1: "Состоялась",
    status: 1,
    classname: "contlogo logo1",
  },
  {
    date: "03 Марта 2021 ",
    name: "Никитина Ольга ",
    hour: "18:00",
    profession: "Оториноларинголог (ЛОР), Терапевт",
    staj: "Стаж 15 лет",
    contbut: "Запланировано",
    contbut1: "Состоялась",
    status: 1,
    classname: "contlogo logo2",
  },

  {
    date: "03 Марта 2021 ",
    name: "Ольга Никитина",
    hour: "14:00",
    profession: "Оториноларинголог (ЛОР), Терапевт",
    staj: "Стаж 15 лет",
    contbut: "Запланировано",
    contbut1: "Состоялась",
    status: 1,
    classname: "contlogo logo3",
  },
  {
    classname: "contlogo logo4",
    name: "Ольг Никитина",
    profession: "Оториноларинголог (ЛОР), Терапевт",
    staj: "Стаж 15 лет",
    date: "03 Марта 2021 ",
    hour: "16:00",
    contbut: "Запланировано",
    contbut1: "Состоялась",
    status: 2,
  },
  {
    classname: "contlogo logo4",
    name: "Ольг Никитина",
    profession: "Оториноларинголог (ЛОР), Терапевт",
    staj: "Стаж 15 лет",
    date: "03 Марта 2021 ",
    hour: "16:00",
    contbut: "Запланировано",
    contbut1: "Состоялась",
    status: 2,
  },
  {
    classname: "contlogo logo4",
    name: "Ольг Никитина",
    profession: "Оториноларинголог (ЛОР), Терапевт",
    staj: "Стаж 15 лет",
    date: "03 Марта 2021 ",
    hour: "16:00",
    contbut: "Запланировано",
    contbut1: "Состоялась",
    status: 3,
  },
];
