const BalansArrRu = [
  {
    classname: "balanscontlogo1",
    balansdate: "10.03.2021",
    balansstate: "Пополнение",
    money: "+ 560,00 $",
    classcolor: "balanscolorgreen",
    status: 1,
    id: 3,
  },
  {
    classname: "balanscontlogo2",
    balansdate: "10.03.2021",
    balansstate: "Оплата за консультацию",
    money: "- 660,00 $",
    classcolor: "balanscolorred",
    status: 1,
    id: 3,
  },
  {
    classname: "balanscontlogo1",
    balansdate: "10.03.2021",
    balansstate: "Пополнение",
    money: "+ 440,00 $",
    classcolor: "balanscolorgreen",
    status: 1,
    id: 3,
  },
  {
    classname: "balanscontlogo1",
    balansdate: "8.03.2021",
    balansstate: "Пополнение",
    money: "+ 820,00 $",
    classcolor: "balanscolorgreen",
    status: 2,
    id: 3,
  },
  {
    classname: "balanscontlogo1",
    balansdate: "1.03.2021",
    balansstate: "Пополнение",
    money: "+ 100,00 $",
    classcolor: "balanscolorgreen",
    status: 2,
    id: 3,
  },
  {
    classname: "balanscontlogo2",
    balansdate: "4.03.2021",
    balansstate: "Оплата за консультацию",
    money: "- 240,00 $",
    classcolor: "balanscolorred",
    status: 2,
    id: 3,
  },
];

const BalansArrEn = [
  {
    classname: "balanscontlogo1",
    balansdate: "10.03.2021",
    balansstate: "Replenishment",
    money: "+ 560,00 $",
    classcolor: "balanscolorgreen",
    status: 1,
    id: 3,
  },
  {
    classname: "balanscontlogo2",
    balansdate: "10.03.2021",
    balansstate: "Payment for consultation",
    money: "- 660,00 $",
    classcolor: "balanscolorred",
    status: 1,
    id: 3,
  },
  {
    classname: "balanscontlogo1",
    balansdate: "10.03.2021",
    balansstate: "Replenishment",
    money: "+ 440,00 $",
    classcolor: "balanscolorgreen",
    status: 1,
    id: 3,
  },
  {
    classname: "balanscontlogo1",
    balansdate: "8.03.2021",
    balansstate: "Replenishment",
    money: "+ 820,00 $",
    classcolor: "balanscolorgreen",
    status: 2,
    id: 3,
  },
  {
    classname: "balanscontlogo1",
    balansdate: "1.03.2021",
    balansstate: "Replenishment",
    money: "+ 100,00 $",
    classcolor: "balanscolorgreen",
    status: 2,
    id: 3,
  },
  {
    classname: "balanscontlogo2",
    balansdate: "4.03.2021",
    balansstate: "Payment for consultation",
    money: "- 240,00 $",
    classcolor: "balanscolorred",
    status: 2,
    id: 3,
  },
];
export { BalansArrRu, BalansArrEn };
