const TranslateRu = {
  bodyframe1: "Как пользоваться?",
  bodyframe2: "Мои записи",
  bodyframe3: "Записаться к врачу",
  name: "Имя",
  surname: "Фамилия",
  profil: "Мой профиль",
  balans: "Пополнить баланс",
  FAQ: "FAQ",
  exit: "Выйти",
  hh: "Онлайн консультации от врачей специалистов 24/7",
  p: "Проконсультируйтесь сейчас или по  предварительной записи  со своего компьютера или c помощью нашего приложения, доступного в App Store и Google Play",
  but: "Записаться",
  butt: "Как это работает?",
  bodyh: "Записаться к врачу",
  bodyp: "Более 1500 врачей и более 50 разных специализаций",
  bodyul: "Прием в удобное для вас время, без визита в клинику",
  bodyull: "Врачи с опытом работы более 8 лет",
  bodyulll: "Понятно объясним причину недуга и дадим подробную рекомендацию",
  bodybut: "МОИ ЗАПИСИ",
  bodytableA: "Предстоящие",
  bodytableB: "Прошедшие",
  bodytableC: "Отмененные",
  video: "Видео связь",
  commentname: "Имя Фамилия",
  profession: "Педиатр",
  staj: "Стаж 15 лет",
  contbutt: "Посмотреть запись",
  butcont: "Посмотреть постановление",
  footp:
    "Онлай- консульации специалистов врачей, то что предлагает данный сервис.",
  footp1:
    "В нашем веб и мобильном приложении вы найдете врачей экспертов, которые окажут вам персонализированную помощь онлайн 24/7",
  help1: "Как пользоваться",
  help2: "FAQ (ответы на вопросы)",
  help3: "Для врачей",
  help4: "О сервисе",
  help5: "Контакты",
  help6: "Пользовательское соглашение",
  email: "allodoc@mail.com",
  address: "г. Москва. ул, Ленина 54, офис 51",
  date: "Пн-Вс с 09:00 до 18:00",
  nomer: "8 800 555 35 35",
};
const TranslateEn = {
  bodyframe1: "How to use?",
  bodyframe2: "My notes",
  bodyframe3: "Make an appointment",
  name: "Name",
  surname: "Surname",
  profil: "My profile",
  balans: "Top up balance",
  FAQ: "FAQ",
  exit: "Exit",
  hh: "Online consultations from specialist doctors 24/7",
  p: "Consult now or by appointment from your computer or through our app available on the App Store and Google Play.",
  but: "Enroll",
  butt: "How does it work?",
  bodyh: "Make an appointment",
  bodyp: "More than 1500 doctors and more than 50 different specialties",
  bodyul:
    "Appointments at a time that is convenient for you, without coming to the clinic",
  bodyull: "Doctors with more than 8 years of experience",
  bodyulll:
    "We will explain the cause of the ailment clearly and give a detailed recommendation",
  bodybut: "MY RECORDS",
  bodytableA: "Upcoming",
  bodytableB: "Past",
  bodytableC: "Canceled",
  video: "liaison",
  contbutt: "Scheduled",
  commentname: "Name Surname",
  profession: "Pediatrician",
  staj: "15 years of experience",
  butcont: "View the ruling",
  footp:
    "Online consultations with specialist doctors, what this service offers.",
  footp1:
    "In our web and mobile application you will find expert doctors who will provide you with personalized care online 24/7",
  help1: "How to use",
  help2: "FAQ (answers on questions)",
  help3: "For doctors",
  help4: "About the service",
  help5: "Contacts",
  help6: "Terms of use",
  email: "allodoc@mail.com",
  address: "Moscow city. st., Lenina 54, office 51",
  date: "Mon-Sun from 09:00 to 18:00",
  nomer: "8 800 555 35 35",
};
export { TranslateRu, TranslateEn };
