export const CommentArrayRu = [
  {
    date: "03 Марта 2021 ",
    name: "Ольга Никитина",
    hour: "16:00",
    profession: "Педиатр",
    staj: "Стаж 15 лет",
    contbut: "Запланировано",
    status: 1,
    classname: "contlogo logo1",
    class: "contbutt1",
    id: 1,
    money: "30 $ / консультация",
    minut: "30 минут",
    zapis: "Ближайшая запись",
    zapisdate: "Вторник 03 Марта",
    education: "Ближайшая запись",
    educationp: "1992 - Российский Государственный Университет",
    educationp1: "1994 - Ординатура по специальности «Педиатрия»",
    masnagitutyun: "Специализируется на лечении",
    lorem: `Lorem ipsum dolor sit amet, consectetur adipiscing elit,
     sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
       nisi ut aliquip ex ea commodo consequat.`,
    lracucich: "Дополнительно",
    vrach: "Врачи",
    pediatr: "Педиатр",
    profilvrach: "Профиль врача",
  },
  {
    date: "03 Марта 2021 ",
    name: "Никитина Ольга ",
    hour: "18:00",
    profession: "Оториноларинголог (ЛОР), Терапевт",
    staj: "Стаж 15 лет",
    contbut: "Запланировано",
    status: 1,
    classname: "contlogo logo2",
    class: "contbutt1",
    id: 2,
    money: "30 $ / консультация",
    minut: "30 минут",
    zapis: "Ближайшая запись",
    zapisdate: "Вторник 03 Марта",
    education: "Ближайшая запись",
    educationp: "1992 - Российский Государственный Университет",
    educationp1: "1994 - Ординатура по специальности «Педиатрия»",
    masnagitutyun: "Специализируется на лечении",
    lorem: `Lorem ipsum dolor sit amet, consectetur adipiscing elit,
     sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
       nisi ut aliquip ex ea commodo consequat.`,
    lracucich: "Дополнительно",
    vrach: "Врачи",
    pediatr: "Педиатр",
    profilvrach: "Профиль врача",
  },

  {
    classname: "contlogo logo4",
    name: "Ольг Никит",
    profession: "Оториноларинголог (ЛОР), Терапевт",
    staj: "Стаж 15 лет",
    date: "03 Марта 2021 ",
    hour: "16:00",
    class: "contbutt",
    contbut: "Состоялась",
    status: 2,
    id: 3,
    money: "30 $ / консультация",
    minut: "30 минут",
    zapis: "Ближайшая запись",
    zapisdate: "Вторник 03 Марта",
    education: "Ближайшая запись",
    educationp: "1992 - Российский Государственный Университет",
    educationp1: "1994 - Ординатура по специальности «Педиатрия»",
    masnagitutyun: "Специализируется на лечении",
    lorem: `Lorem ipsum dolor sit amet, consectetur adipiscing elit,
     sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
       nisi ut aliquip ex ea commodo consequat.`,
    lracucich: "Дополнительно",
    vrach: "Врачи",
    pediatr: "Педиатр",
    profilvrach: "Профиль врача",
  },
  {
    classname: "contlogo logo4",
    name: "Ольг Фамилия",
    profession: "Оториноларинголог (ЛОР), Терапевт",
    staj: "Стаж 15 лет",
    date: "03 Марта 2021 ",
    hour: "16:00",
    class: "contbutt",
    contbut: "Состоялась",
    status: 2,
    id: 4,
    money: "30 $ / консультация",
    minut: "30 минут",
    zapis: "Ближайшая запись",
    zapisdate: "Вторник 03 Марта",
    education: "Ближайшая запись",
    educationp: "1992 - Российский Государственный Университет",
    educationp1: "1994 - Ординатура по специальности «Педиатрия»",
    masnagitutyun: "Специализируется на лечении",
    lorem: `Lorem ipsum dolor sit amet, consectetur adipiscing elit,
     sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
       nisi ut aliquip ex ea commodo consequat.`,
    lracucich: "Дополнительно",
    vrach: "Врачи",
    pediatr: "Педиатр",
    profilvrach: "Профиль врача",
  },
  {
    classname: "contlogo logo4",
    name: "Имя Никитина",
    profession: "Оториноларинголог (ЛОР), Терапевт",
    staj: "Стаж 15 лет",
    date: "03 Марта 2021 ",
    hour: "16:00",
    status: 3,
    contbut: "Отменено",
    class: "contbutt2",
    id: 5,
    money: "30 $ / консультация",
    minut: "30 минут",
    zapis: "Ближайшая запись",
    zapisdate: "Вторник 03 Марта",
    education: "Ближайшая запись",
    educationp: "1992 - Российский Государственный Университет",
    educationp1: "1994 - Ординатура по специальности «Педиатрия»",
    masnagitutyun: "Специализируется на лечении",
    lorem: `Lorem ipsum dolor sit amet, consectetur adipiscing elit,
     sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
       nisi ut aliquip ex ea commodo consequat.`,
    lracucich: "Дополнительно",
    vrach: "Врачи",
    pediatr: "Педиатр",
    profilvrach: "Профиль врача",
  },
  {
    classname: "contlogo logo4",
    name: "Имя Фамилия",
    profession: "Оториноларинголог (ЛОР), Терапевт",
    staj: "Стаж 15 лет",
    date: "03 Марта 2021 ",
    hour: "16:00",
    status: 3,
    contbut: "Отменено",
    class: "contbutt2",
    id: 6,
    money: "30 $ / консультация",
    minut: "30 минут",
    zapis: "Ближайшая запись",
    zapisdate: "Вторник 03 Марта",
    education: "Ближайшая запись",
    educationp: "1992 - Российский Государственный Университет",
    educationp1: "1994 - Ординатура по специальности «Педиатрия»",
    masnagitutyun: "Специализируется на лечении",
    lorem: `Lorem ipsum dolor sit amet, consectetur adipiscing elit,
     sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
       nisi ut aliquip ex ea commodo consequat.`,
    lracucich: "Дополнительно",
    vrach: "Врачи",
    pediatr: "Педиатр",
    profilvrach: "Профиль врача",
  },
];

export const CommentArrayEn = [
  {
    date: "03 Mart 2021 ",
    name: "Olga Nikitina",
    hour: "16:00",
    profession: "Pediatrician",
    staj: "15 years of experience",
    contbut: "Planned",
    status: 1,
    classname: "contlogo logo1",
    class: "contbutt1",
    id: 1,
    money: "$30/consultation",
    minut: "30 minut",
    zapis: "Nearest entry",
    zapisdate: "Tuesday 03 March",
    education: "Nearest entry",
    educationp: "1992 - Russian State University",
    educationp1: "1994 - Residency in Pediatrics",
    masnagitutyun: "Specializes in treatment",
    lorem: `Lorem ipsum dolor sit amet, consectetur adipiscing elit,
     sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
       nisi ut aliquip ex ea commodo consequat.`,
    lracucich: "Additionally",
    vrach: "Doctors",
    pediatr: "Pediatrician",
    profilvrach: "Doctor's profile",
  },
  {
    date: "03 Mart 2021 ",
    name: " Nikitina Olga",
    hour: "16:00",
    profession: "Pediatrician",
    staj: "15 years of experience",
    contbut: "Planned",
    status: 1,
    money: "$30/consultation",
    minut: "30 minut",
    zapis: "Nearest entry",
    zapisdate: "Tuesday 03 March",
    education: "Nearest entry",
    educationp: "1992 - Russian State University",
    educationp1: "1994 - Residency in Pediatrics",
    masnagitutyun: "Specializes in treatment",
    lorem: `Lorem ipsum dolor sit amet, consectetur adipiscing elit,
     sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
       nisi ut aliquip ex ea commodo consequat.`,
    lracucich: "Additionally",
    vrach: "Doctors",
    pediatr: "Pediatrician",
    profilvrach: "Doctor's profile",
    classname: "contlogo logo2",
    class: "contbutt1",
    id: 2,
  },

  {
    classname: "contlogo logo4",
    class: "contbutt",
    id: 3,
    date: "03 Mart 2021 ",
    name: "Name Nik",
    hour: "16:00",
    profession: "Pediatrician",
    staj: "15 years of experience",
    contbut: "Held",
    status: 2,
    money: "$30/consultation",
    minut: "30 minut",
    zapis: "Nearest entry",
    zapisdate: "Tuesday 03 March",
    education: "Nearest entry",
    educationp: "1992 - Russian State University",
    educationp1: "1994 - Residency in Pediatrics",
    masnagitutyun: "Specializes in treatment",
    lorem: `Lorem ipsum dolor sit amet, consectetur adipiscing elit,
     sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
       nisi ut aliquip ex ea commodo consequat.`,
    lracucich: "Additionally",
    vrach: "Doctors",
    pediatr: "Pediatrician",
    profilvrach: "Doctor's profile",
  },
  {
    classname: "contlogo logo4",
    id: 4,
    class: "contbutt",
    date: "03 Mart 2021 ",
    name: "Olga",
    hour: "16:00",
    profession: "Pediatrician",
    staj: "15 years of experience",
    contbut: "Held",
    status: 2,
    money: "$30/consultation",
    minut: "30 minut",
    zapis: "Nearest entry",
    zapisdate: "Tuesday 03 March",
    education: "Nearest entry",
    educationp: "1992 - Russian State University",
    educationp1: "1994 - Residency in Pediatrics",
    masnagitutyun: "Specializes in treatment",
    lorem: `Lorem ipsum dolor sit amet, consectetur adipiscing elit,
     sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
       nisi ut aliquip ex ea commodo consequat.`,
    lracucich: "Additionally",
    vrach: "Doctors",
    pediatr: "Pediatrician",
    profilvrach: "Doctor's profile",
  },
  {
    classname: "contlogo logo4",
    class: "contbutt2",
    id: 5,

    date: "03 Mart 2021 ",
    name: "Olga Surname",
    hour: "16:00",
    profession: "Pediatrician",
    staj: "15 years of experience",
    contbut: "Canceled",
    status: 3,
    money: "$30/consultation",
    minut: "30 minut",
    zapis: "Nearest entry",
    zapisdate: "Tuesday 03 March",
    education: "Nearest entry",
    educationp: "1992 - Russian State University",
    educationp1: "1994 - Residency in Pediatrics",
    masnagitutyun: "Specializes in treatment",
    lorem: `Lorem ipsum dolor sit amet, consectetur adipiscing elit,
     sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
       nisi ut aliquip ex ea commodo consequat.`,
    lracucich: "Additionally",
    vrach: "Doctors",
    pediatr: "Pediatrician",
    profilvrach: "Doctor's profile",
  },
  {
    classname: "contlogo logo4",
    class: "contbutt2",
    id: 6,

    date: "03 Mart 2021 ",
    name: "Ol Nik",
    hour: "16:00",
    profession: "Pediatrician",
    staj: "15 years of experience",
    contbut: "Canceled",
    status: 3,
    money: "$30/consultation",
    minut: "30 minut",
    zapis: "Nearest entry",
    zapisdate: "Tuesday 03 March",
    education: "Nearest entry",
    educationp: "1992 - Russian State University",
    educationp1: "1994 - Residency in Pediatrics",
    masnagitutyun: "Specializes in treatment",
    lorem: `Lorem ipsum dolor sit amet, consectetur adipiscing elit,
     sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
      Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
       nisi ut aliquip ex ea commodo consequat.`,
    lracucich: "Additionally",
    vrach: "Doctors",
    pediatr: "Pediatrician",
    profilvrach: "Doctor's profile",
  },
];
